# Generated by Django 4.1 on 2022-12-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inscripcion', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('RE', 'RESERVADO'), ('CO', 'COMPLETADA'), ('AN', 'ANULADA'), ('NA', 'NO ASISTEN')], default='RE', max_length=255)),
                ('observacion', models.CharField(max_length=255)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.institucion')),
            ],
        ),
    ]
