# Generated by Django 4.1 on 2022-12-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='estado',
            field=models.CharField(blank=True, choices=[('RE', 'RESERVADO'), ('CO', 'COMPLETADA'), ('AN', 'ANULADA'), ('NA', 'NO ASISTEN')], default='RE', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.institucion'),
        ),
    ]
