# Generated by Django 4.1 on 2022-12-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_participante_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='estado',
            field=models.CharField(blank=True, choices=[('RE', 'Reservado'), ('CO', 'Completada'), ('AN', 'Anulada'), ('NA', 'No asiste')], default='RE', max_length=255, null=True),
        ),
    ]
