# Generated by Django 4.1 on 2022-12-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_participante_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='estado',
            field=models.CharField(blank=True, choices=[('Reservado', 'Reservado'), ('Completado', 'Completada'), ('Anulado', 'Anulada'), ('No Asiste', 'No asiste')], default='Reservado', max_length=255, null=True),
        ),
    ]
